### ISSUE TITLE
price dont work

### ISSUE THREAD

**Issue by voldedk** [RenewedPlains/codeswholesale-woocommerce-patch#5]
price dont work.. it set all my products to the same price when auto update price and stock is disable, but when it is enable, it set all my products to 0,- ... please fix

**Comment by RenewedPlains** [comment]
Hello @voldedk,

due to the conversion of codeswholesale direct, the structure had to be adjusted. The price structure has changed fundamentally in the API. Codeswholesale has changed this negligently without communication. 

Our patch officially supports the new API structure as of today. 

Feel free to try the new plugin 0.9.5 and let me know if the plugin works for you like this. Please make sure that you have already set the API keys in the Bojett settings before you start an import. It seems like the settings control is currently unavailable. I will correct this soon. :) 

Thanks for your support and use of our plugin!
